### ISSUE TITLE
Experiment with unbiased composition

### ISSUE THREAD

**Issue by freebroccolo** [freebroccolo/agda-cubical-sets#9]
I've gotten closer to defining the machinery for unbiased composition for arbitrary globular pasting diagrams but there are still some issues to be sorted out. However, we should still be able to define a notion of unbiased composition for lower dimensional diagrams directly and use this for the formalization of categories, etc.

**Comment by jonsterling** [comment]
Very interesting. Could you show me an example of what unbiased composition means/might look like?

**Comment by freebroccolo** [comment]
@jonsterling Yeah. I had an example here earlier but I removed it momentarily since I thought there might be a problem with the coherence laws. But I think it might be okay actually. Here's what I had cooked up (keeping in mind it needs to be weakened for E-categories):

![unbiased](https://cloud.githubusercontent.com/assets/151197/23384604/f6ed6590-fd08-11e6-9a0a-c8132ba90718.png)

It lo that this representation is equivalent to viewing a category as a kind of algebra for the monad induced by the free category on a graph (which is related to the nerve construction). See [here](https://en.wikipedia.org/wiki/Monad_(category_theory)#Algebras_for_a_monad), where `cmp` is like the structure map.

**Comment by freebroccolo** [comment]
Just to add a bit of context: this is supposed to be a special case of how composition should work for globular pasting diagrams because the globular pasting diagrams are to the free strict ∞-category monad (on a globular set) what paths are to the free category monad (on a graph).

**Comment by jonsterling** [comment]
Ahh! I recognize this now. cool!

**Comment by jonsterling** [comment]
I don't yet have an intuition for whether this would simplify proofs; do you think it would? If so, that'd be pretty sweet...

**Comment by freebroccolo** [comment]
@jonsterling It's hard to say for sure yet. There are some cases where I think having this would have resulted in cleaner definitions and proofs but it's possible that that would be offset by more complexity elsewhere.

Where it starts to become more interesting is when higher dimensional structure comes into play because then the apparently simplicity of binary composition starts to become a liability due to the explosion in coherence laws.

I suspect if we could make this version usable it would also be easier to automate certain proofs just due to the uniformity, especially if we can get composition to work smoothly across dimensions.

**Comment by freebroccolo** [comment]
@jonsterling Here's a more realistic version. It's still missing the whiskering operation but that should be straightforward. Seems promising so far.

![unbiased](https://cloud.githubusercontent.com/assets/151197/23390168/a8c5189c-fd29-11e6-9643-bae994a0ad2d.png)

**Comment by freebroccolo** [comment]
Here's a rough version with whiskering. One reason it would be nice to do this with globular pasting diagrams, even if we only use 3 dimensions in practice, is that it would allow us to have a single path structure and `wsk` would reduce to a special case of `cmp`.

But even like this I think it could be an improvement over the version with binary composition. One of the issues with implementing a solver for the categorical proofs using reflection is that you will essentially have to do something like NBE for monoids where you flatten the tree structure by re-associating all of the compositions to the right. It seems like a lot of that machinery in the solver would be unnecessary if we started with an unbiased representation to begin with. 

```agda
module Pasting where

module _ {A : Set} where
  infixr 5 _∷_
  data VSeq (Ψ₀ : A → A → Set) (x : A) : A → Set where
    []
      : VSeq Ψ₀ x x
    _∷_
      : ∀ {y z}
      → (f : Ψ₀ x y)
      → (π : VSeq Ψ₀ y z)
      → VSeq Ψ₀ x z

  module _ {Ψ₀ : (x y : A) → Set} where
    map₀
      : (R₀ : A → A → Set)
      → (k₀ : ∀ {a b} → Ψ₀ a b → R₀ a b)
      → ∀ {x y}
      → VSeq Ψ₀ x y → VSeq R₀ x y
    map₀ R₀ k₀ [] = []
    map₀ R₀ k₀ (f ∷ π) = k₀ f ∷ map₀ R₀ k₀ π

    pure₀ : ∀ {x y} → Ψ₀ x y → VSeq Ψ₀ x y
    pure₀ f = f ∷ []

    join₀ : ∀ {x y} → VSeq (VSeq Ψ₀) x y → VSeq Ψ₀ x y
    join₀ [] = []
    join₀ ([] ∷ π) = join₀ π
    join₀ ((f ∷ π₀) ∷ π₁) = f ∷ join₀ (π₀ ∷ π₁)

module _ {A : Set} {Ψ₀ : (x y : A) → Set} where
  infixr 5 _∷_
  data HSeq (Ψ₁ : ∀ {x y} (f g : Ψ₀ x y) → Set) : ∀ {x y} (f g : VSeq {A} Ψ₀ x y) → Set where
    []
      : ∀ {x y} {f : VSeq Ψ₀ x y}
      → HSeq Ψ₁ f f
    _∷_
      : ∀ {x y z} {π₀ π₁ : VSeq Ψ₀ y z} {f₀ f₁ : Ψ₀ x y}
      → Ψ₁ f₀ f₁
      → HSeq Ψ₁ π₀ π₁
      → HSeq Ψ₁ (f₀ ∷ π₀) (f₁ ∷ π₁)

record ΔCategory : Set where
  no-eta-equality
  field
    col : Globular
    seq : ∀ {x y} → VSeq (λ a b → col .∂ a b .●) x y → col .∂ x y .●
    wsk : ∀ {x y} f g → HSeq (λ {a}{b} → λ k₀ k₁ → col .∂ a b .∂ k₀ k₁ .●) f g → col .∂ x y .∂ (seq f) (seq g) .●
  field
    idn₁ : ∀ {x y f}
      → col .∂ x y .∂ f f .●
    cmp₁ : ∀ {x y f g h}
      → (β : col .∂ x y .∂ g h .●) (α : col .∂ x y .∂ f g .●)
      → col .∂ x y .∂ f h .●
    inv₁ : ∀ {x y f g}
      → (α : col .∂ x y .∂ f g .●)
      → col .∂ x y .∂ g f .●
  field
    coh-pure : ∀ {x y} f → col .∂ x y .∂ (seq (pure₀ f)) f .●
    coh-join : ∀ {x y} π → col .∂ x y .∂ (seq (map₀ (λ a b → col .∂ a b .●) seq π)) (seq (join₀ π)) .●
open ΔCategory public

ΔSetoid : ΔCategory
ΔSetoid .col .● = Setoid
ΔSetoid .col .∂ 𝒳 𝒴 .● = S.Map 𝒳 𝒴
ΔSetoid .col .∂ 𝒳 𝒴 .∂ F G .● = ∀ {x} → S.hom 𝒴 (ap₀ F x) (ap₀ G x)
ΔSetoid .col .∂ 𝒳 𝒴 .∂ F G .∂ α β = G.𝟘
ΔSetoid .seq [] = S.idn
ΔSetoid .seq (F ∷ π) = S.cmp (ΔSetoid .seq π) F
ΔSetoid .wsk {𝒳}{𝒴} [] [] [] = S.idn₀ 𝒳
ΔSetoid .wsk {𝒳}{𝒴} (F ∷ π) _ [] = ΔSetoid .wsk π π []
ΔSetoid .wsk {𝒳}{𝒴} (F ∷ π₀) (G ∷ π₁) (α ∷ π₂) = cmp₀ 𝒴 (ap₁ (seq ΔSetoid π₁) α) (ΔSetoid .wsk π₀ π₁ π₂)
ΔSetoid .idn₁ {𝒳}{𝒴} = S.idn₀ 𝒴
ΔSetoid .cmp₁ {𝒳}{𝒴} α β {x} = S.cmp₀ 𝒴 (α {x}) (β {x})
ΔSetoid .inv₁ {𝒳}{𝒴} α {x} = S.inv₀ 𝒴 (α {x})
ΔSetoid .coh-pure {𝒳}{𝒴} F = S.idn₀ 𝒴
ΔSetoid .coh-join {𝒳}{_} [] {x} = S.idn₀ 𝒳
ΔSetoid .coh-join {𝒳}{𝒴} ([] ∷ π) {x} = ΔSetoid .coh-join π
ΔSetoid .coh-join {𝒳}{𝒴} ((F ∷ π₀) ∷ π₁) {x} = ΔSetoid .coh-join (π₀ ∷ π₁)

postulate
  A B C D : Setoid
  F₀ F₁ : S.Map A B
  G₀ G₁ : S.Map B C
  H₀ H₁ : S.Map C D
  α : ∀ {x} → S.hom B (ap₀ F₀ x) (ap₀ F₁ x)
  β : ∀ {x} → S.hom C (ap₀ G₀ x) (ap₀ G₁ x)
  γ : ∀ {x} → S.hom D (ap₀ H₀ x) (ap₀ H₁ x)

ex₀ : VSeq S.Map A D
ex₀ = F₀ ∷ G₀ ∷ H₀ ∷ []

ex₁ : VSeq S.Map A D
ex₁ = F₁ ∷ G₁ ∷ H₁ ∷ []

ex₂ : ∀ {x} → S.hom D (ΔSetoid .seq ex₀ .ap₀ x) (ΔSetoid .seq ex₁ .ap₀ x)
ex₂ = ΔSetoid .wsk ex₀ ex₁ (α ∷ β ∷ γ ∷ [])
```
